# Generated by Django 4.2.7 on 2025-10-05 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitLossScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('scenario_type', models.CharField(choices=[('profit', 'Profit Scenario'), ('loss', 'Loss Scenario'), ('mixed', 'Mixed Scenario')], max_length=10)),
                ('percentage_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('time_duration', models.IntegerField()),
                ('time_unit', models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=10)),
                ('apply_to_all_investments', models.BooleanField(default=False)),
                ('apply_to_all_users', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('execute_immediately', models.BooleanField(default=False)),
                ('scheduled_execution', models.DateTimeField(blank=True, null=True)),
                ('repeat_execution', models.BooleanField(default=False)),
                ('repeat_interval_hours', models.IntegerField(default=24)),
                ('times_executed', models.IntegerField(default=0)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('next_execution', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_admin_scenarios', to=settings.AUTH_USER_MODEL)),
                ('target_crypto_index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_scenarios', to='trades.cryptoindex')),
                ('target_cryptocurrency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_scenarios', to='trades.cryptocurrency')),
            ],
            options={
                'verbose_name': 'Profit/Loss Scenario',
                'verbose_name_plural': 'Profit/Loss Scenarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('profit_loss_mode', models.CharField(choices=[('manual', 'Manual Control'), ('automatic', 'Automatic Based on Market'), ('simulated', 'Simulated Trading'), ('custom', 'Custom Scenarios')], default='automatic', max_length=10)),
                ('default_profit_rate', models.DecimalField(decimal_places=4, default=5.0, max_digits=10)),
                ('default_loss_rate', models.DecimalField(decimal_places=4, default=2.0, max_digits=10)),
                ('max_profit_rate', models.DecimalField(decimal_places=4, default=100.0, max_digits=10)),
                ('max_loss_rate', models.DecimalField(decimal_places=4, default=50.0, max_digits=10)),
                ('index_appreciation_rate', models.DecimalField(decimal_places=4, default=10.0, max_digits=10)),
                ('index_depreciation_rate', models.DecimalField(decimal_places=4, default=5.0, max_digits=10)),
                ('index_volatility_factor', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('price_update_frequency', models.IntegerField(default=1)),
                ('investment_update_frequency', models.IntegerField(default=5)),
                ('portfolio_calculation_frequency', models.IntegerField(default=10)),
                ('min_trade_amount', models.DecimalField(decimal_places=8, default=0.001, max_digits=20)),
                ('max_trade_amount', models.DecimalField(decimal_places=8, default=100.0, max_digits=20)),
                ('min_investment_amount', models.DecimalField(decimal_places=8, default=0.01, max_digits=20)),
                ('trading_fee_percentage', models.DecimalField(decimal_places=4, default=0.001, max_digits=5)),
                ('withdrawal_fee_percentage', models.DecimalField(decimal_places=4, default=0.005, max_digits=5)),
                ('management_fee_percentage', models.DecimalField(decimal_places=4, default=0.02, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trading Settings',
                'verbose_name_plural': 'Trading Settings',
            },
        ),
        migrations.CreateModel(
            name='ScenarioExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('affected_investments', models.IntegerField(default=0)),
                ('affected_users', models.IntegerField(default=0)),
                ('total_value_change', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='admin_control.profitlossscenario')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
