# Generated by Django 4.2.7 on 2025-10-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0002_marketdatasimulation_usertradeoutcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsettings',
            name='active_duration_seconds',
            field=models.IntegerField(default=300, help_text='Trade duration in active mode (seconds)'),
        ),
        migrations.AddField(
            model_name='tradingsettings',
            name='active_loss_percentage',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Loss percentage when users are actively trading', max_digits=5),
        ),
        migrations.AddField(
            model_name='tradingsettings',
            name='idle_duration_seconds',
            field=models.IntegerField(default=1800, help_text='Trade duration in idle mode (seconds)'),
        ),
        migrations.AddField(
            model_name='tradingsettings',
            name='idle_profit_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Profit percentage when no users are actively trading', max_digits=5),
        ),
    ]
