# Generated by Django 4.2.7 on 2025-10-11 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0003_tradingsettings_active_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsettings',
            name='active_profit_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Profit percentage when users win in active mode', max_digits=5),
        ),
        migrations.AddField(
            model_name='tradingsettings',
            name='active_win_rate_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Probability of profit when users are actively trading (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='active_loss_percentage',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Loss percentage when users lose in active mode', max_digits=5),
        ),
    ]
