# Generated by Django 4.2.7 on 2025-10-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0004_add_active_mode_profit_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsettings',
            name='use_real_prices',
            field=models.BooleanField(default=False, help_text='Use real cryptocurrency prices from exchanges (CoinGecko/CCXT)'),
        ),
    ]
