# Generated by Django 4.2.7 on 2025-10-05 23:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('strategy_type', models.CharField(choices=[('dca', 'Dollar Cost Averaging'), ('grid', 'Grid Trading'), ('momentum', 'Momentum Trading'), ('mean_reversion', 'Mean Reversion'), ('arbitrage', 'Arbitrage'), ('custom', 'Custom Strategy')], max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed')], default='paused', max_length=10)),
                ('parameters', models.JSONField(default=dict)),
                ('max_position_size', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_loss_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('take_profit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('total_pnl', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_pnl', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('daily_trades', models.IntegerField(default=0)),
                ('daily_win_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('cumulative_pnl', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('cumulative_trades', models.IntegerField(default=0)),
                ('cumulative_win_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('max_drawdown', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('volatility', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='strategy_engine.tradingstrategy')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StrategyExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold'), ('stop', 'Stop'), ('adjust', 'Adjust Position')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('reason', models.TextField()),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('market_conditions', models.JSONField(default=dict)),
                ('strategy_parameters', models.JSONField(default=dict)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='strategy_engine.tradingstrategy')),
            ],
            options={
                'ordering': ['-execution_time'],
            },
        ),
        migrations.CreateModel(
            name='StrategyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('profit_target', 'Profit Target Reached'), ('stop_loss', 'Stop Loss Triggered'), ('position_limit', 'Position Limit Reached'), ('strategy_error', 'Strategy Error'), ('market_condition', 'Market Condition Change'), ('custom', 'Custom Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('alert_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='strategy_engine.tradingstrategy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tradingstrategy',
            index=models.Index(fields=['user', 'is_active'], name='strategy_en_user_id_aa866d_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingstrategy',
            index=models.Index(fields=['strategy_type', 'is_active'], name='strategy_en_strateg_95283e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyperformance',
            unique_together={('strategy', 'date')},
        ),
    ]
