services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fluxor_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - trading_network

  # Redis Cache and Message Broker
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - trading_network

  # Django API
  api:
    build:
      context: ./fluxor_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fluxor_api
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev-secret-key-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3001
    volumes:
      - ./fluxor_api:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - trading_network

  # Next.js Web Application
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - PORT=5173
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - api
    networks:
      - trading_network

  # Celery Worker
  celery_worker:
    build:
      context: ./fluxor_api
      dockerfile: Dockerfile
    command: celery -A fluxor_api worker -l info
    volumes:
      - ./fluxor_api:/app
    environment:
      - DJANGO_SETTINGS_MODULE=fluxor_api.settings
      - DB_HOST=db
      - DB_NAME=fluxor_api
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - trading_network

  # Celery Beat (Scheduler)
  celery_beat:
    build:
      context: ./fluxor_api
      dockerfile: Dockerfile
    command: celery -A fluxor_api beat -l info
    volumes:
      - ./fluxor_api:/app
    environment:
      - DJANGO_SETTINGS_MODULE=fluxor_api.settings
      - DB_HOST=db
      - DB_NAME=fluxor_api
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - trading_network


  # Fluxor Dashboard - Simple HTTP Server
  dashboard:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - ./fluxor-dashboard/dist:/usr/share/nginx/html
      - ./fluxor-dashboard/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - trading_network

  # Trading Tasks Service (Automated Financial Updates)
  trading_tasks:
    build:
      context: ./fluxor_api
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./fluxor_api:/app
    environment:
      - DJANGO_SETTINGS_MODULE=fluxor_api.settings
      - DB_HOST=db
      - DB_NAME=fluxor_api
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - trading_network

  # pgAdmin Database Management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fluxor.pro
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - trading_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
      - dashboard
    networks:
      - trading_network

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  pgadmin_data:

networks:
  trading_network:
    driver: bridge