version: '3.8'

services:
  # Override frontend for production
  frontend:
    build:
      context: ./fluxor_api/src
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
      - NODE_ENV=production
    volumes: []  # Remove volume mounts for production

  # Override Django for production
  web:
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn fluxor_api.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    environment:
      - DJANGO_SETTINGS_MODULE=fluxor_api.settings.production
      - DB_HOST=db
      - DB_NAME=fluxor_api
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/0
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0

  # Remove trading_tasks in production (use Celery Beat instead)
  trading_tasks:
    deploy:
      replicas: 0