#!/bin/bash

# Fluxor Trading Platform - Subdomain Setup Script
# This script helps configure the subdomain structure for production deployment

set -e

echo "🌐 Fluxor Trading Platform - Subdomain Configuration"
echo "=================================================="

# Configuration
DOMAIN="fluxor.pro"
SUBDOMAINS=("api" "dashboard" "db")
SERVER_IP="YOUR_SERVER_IP"  # Replace with your actual server IP

echo ""
echo "📋 Required DNS Configuration:"
echo "============================="
echo ""
echo "Create the following A records in your DNS provider:"
echo ""
echo "Record Type | Name                | Value"
echo "-----------|---------------------|------------------"
echo "A          | fluxor.pro          | $SERVER_IP"
echo "A          | www.fluxor.pro     | $SERVER_IP"
echo "A          | api.fluxor.pro     | $SERVER_IP"
echo "A          | dashboard.fluxor.pro| $SERVER_IP"
echo "A          | db.fluxor.pro      | $SERVER_IP"
echo ""

echo ""
echo "🔧 Service Configuration:"
echo "========================"
echo ""
echo "Subdomain           | Service    | Port | Purpose"
echo "--------------------|------------|------|------------------"
echo "fluxor.pro         | Frontend   | 3000 | Main trading app"
echo "api.fluxor.pro      | Backend    | 8000 | REST API"
echo "dashboard.fluxor.pro| Dashboard  | 3001 | Admin dashboard"
echo "db.fluxor.pro       | pgAdmin    | 5050 | Database management"
echo ""

echo "🔒 Security Configuration:"
echo "=========================="
echo ""
echo "Access Level:"
echo "- fluxor.pro: Public access"
echo "- api.fluxor.pro: Public with authentication"
echo "- dashboard.fluxor.pro: Superuser authentication required"
echo "- db.fluxor.pro: Basic auth + database credentials"
echo ""

echo "📝 Environment Variables:"
echo "========================="
echo ""
echo "Update your production environment file with:"
echo ""
echo "ALLOWED_HOSTS=fluxor.pro,www.fluxor.pro,api.fluxor.pro,dashboard.fluxor.pro,db.fluxor.pro,localhost,127.0.0.1"
echo "CORS_ALLOWED_ORIGINS=https://fluxor.pro,https://dashboard.fluxor.pro"
echo "VITE_API_BASE_URL=https://api.fluxor.pro"
echo "VITE_WS_BASE_URL=wss://api.fluxor.pro"
echo "VITE_DASHBOARD_URL=https://dashboard.fluxor.pro"
echo ""

echo "🔐 SSL Certificate Setup:"
echo "========================="
echo ""
echo "After DNS propagation (usually 5-15 minutes), run:"
echo ""
echo "certbot certonly --nginx -d fluxor.pro -d www.fluxor.pro -d api.fluxor.pro -d dashboard.fluxor.pro -d db.fluxor.pro"
echo ""

echo "🚀 Deployment Commands:"
echo "======================="
echo ""
echo "1. Update environment variables:"
echo "   cp env.production .env"
echo ""
echo "2. Deploy with Docker Compose:"
echo "   docker-compose -f docker-compose.prod.yml up -d"
echo ""
echo "3. Verify all services:"
echo "   docker-compose ps"
echo ""

echo "✅ Health Check URLs:"
echo "===================="
echo ""
echo "After deployment, verify these URLs:"
echo "- https://fluxor.pro (Main trading app)"
echo "- https://api.fluxor.pro/health/ (API health)"
echo "- https://dashboard.fluxor.pro (Admin dashboard)"
echo "- https://db.fluxor.pro (Database admin)"
echo ""

echo "📊 Monitoring:"
echo "=============="
echo ""
echo "View logs:"
echo "docker-compose logs -f"
echo ""
echo "View specific service logs:"
echo "docker-compose logs -f nginx"
echo "docker-compose logs -f web"
echo "docker-compose logs -f frontend"
echo "docker-compose logs -f dashboard"
echo ""

echo "🎯 Next Steps:"
echo "=============="
echo "1. Configure DNS records as shown above"
echo "2. Wait for DNS propagation (5-15 minutes)"
echo "3. Update environment variables"
echo "4. Deploy with Docker Compose"
echo "5. Generate SSL certificates"
echo "6. Test all subdomains"
echo ""

echo "📚 Documentation:"
echo "================="
echo "See SUBDOMAIN_CONFIGURATION.md for detailed setup instructions"
echo ""

echo "✨ Fluxor Trading Platform is ready for production deployment!"
