# Generated by Django 4.2.7 on 2025-10-05 23:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('trade', 'Trade'), ('dividend', 'Dividend'), ('fee', 'Fee'), ('transfer', 'Transfer')], max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fees', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio_management.portfolio')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('average_cost', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='portfolio_management.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='PnLRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_pnl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('total_return', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('daily_return', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('max_drawdown', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('volatility', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnl_records', to='portfolio_management.portfolio')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('portfolio', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AssetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('target_allocation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='portfolio_management.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'symbol')},
            },
        ),
    ]
