# Generated by Django 4.2.7 on 2025-10-06 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file_uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_front', 'ID Card Front'), ('id_back', 'ID Card Back'), ('passport', 'Passport'), ('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('selfie', 'Selfie with ID')], max_length=20)),
                ('file', models.FileField(upload_to=file_uploads.models.kyc_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='uploaded', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_uploads', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Upload',
                'verbose_name_plural': 'KYC Uploads',
                'db_table': 'kyc_uploads',
                'ordering': ['-uploaded_at'],
                'unique_together': {('user', 'document_type')},
            },
        ),
    ]
