# Generated by Django 4.2.7 on 2025-10-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_deposit_deposit_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='entry_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='is_strategy_trade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_sum',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
