# Generated by Django 4.2.7 on 2025-10-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='verification_documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
