# Generated by Django 4.2.7 on 2025-10-01 12:54

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('portfolio_type', models.CharField(choices=[('spot', 'Spot Trading'), ('margin', 'Margin Trading'), ('futures', 'Futures Trading'), ('options', 'Options Trading')], default='spot', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('max_position_size', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('max_leverage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stop_loss_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_pair', models.CharField(max_length=20)),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('side', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=5)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('average_entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('current_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('unrealized_pnl', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('total_pnl', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('position_value', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('margin_used', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_profit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('leverage', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=5)),
                ('is_open', models.BooleanField(default=True)),
                ('is_hedged', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio_management.portfolio')),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['portfolio', 'is_open'], name='portfolio_m_portfol_9d3d49_idx'), models.Index(fields=['trading_pair', 'is_open'], name='portfolio_m_trading_a39cfb_idx')],
                'unique_together': {('portfolio', 'trading_pair', 'side')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('daily_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('weekly_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monthly_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('volatility', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('open_positions', models.IntegerField(default=0)),
                ('total_positions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolio_management.portfolio')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['portfolio', 'timestamp'], name='portfolio_m_portfol_fc83c5_idx'), models.Index(fields=['timestamp'], name='portfolio_m_timesta_91d37b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1d', '1 Day'), ('1w', '1 Week'), ('1m', '1 Month'), ('3m', '3 Months'), ('6m', '6 Months'), ('1y', '1 Year'), ('all', 'All Time')], max_length=3)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_return', models.DecimalField(decimal_places=4, max_digits=10)),
                ('absolute_return', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('sortino_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('volatility', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('alpha', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('average_trade', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='portfolio_management.portfolio')),
            ],
            options={
                'ordering': ['-end_date'],
                'unique_together': {('portfolio', 'period', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('available_balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('locked_balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('total_balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('usd_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='portfolio_management.portfolio')),
            ],
            options={
                'ordering': ['currency'],
                'unique_together': {('portfolio', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='AssetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('allocation_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency_return', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('contribution_to_return', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='portfolio_management.portfolio')),
            ],
            options={
                'ordering': ['-date', 'allocation_percentage'],
                'unique_together': {('portfolio', 'currency', 'date')},
            },
        ),
    ]
