# Generated by Django 4.2.7 on 2025-10-01 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alert_type', models.CharField(choices=[('price_above', 'Price Above'), ('price_below', 'Price Below'), ('price_change', 'Price Change'), ('volume_spike', 'Volume Spike'), ('technical_signal', 'Technical Signal'), ('news_alert', 'News Alert'), ('portfolio_alert', 'Portfolio Alert'), ('custom', 'Custom Alert')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('trading_pair', models.CharField(blank=True, max_length=20, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('price_change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('repeat_interval', models.IntegerField(blank=True, null=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=False)),
                ('notify_push', models.BooleanField(default=True)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('min_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=10)),
                ('excluded_pairs', models.JSONField(blank=True, default=list)),
                ('excluded_types', models.JSONField(blank=True, default=list)),
                ('batch_notifications', models.BooleanField(default=True)),
                ('notification_delay', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Alert Preference',
                'verbose_name_plural': 'User Alert Preferences',
            },
        ),
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_pair', models.CharField(max_length=20)),
                ('signal_type', models.CharField(choices=[('buy', 'Buy Signal'), ('sell', 'Sell Signal'), ('hold', 'Hold Signal'), ('strong_buy', 'Strong Buy'), ('strong_sell', 'Strong Sell')], max_length=20)),
                ('signal_source', models.CharField(choices=[('technical_analysis', 'Technical Analysis'), ('fundamental_analysis', 'Fundamental Analysis'), ('sentiment_analysis', 'Sentiment Analysis'), ('ai_model', 'AI Model'), ('expert_opinion', 'Expert Opinion'), ('news_event', 'News Event')], max_length=20)),
                ('signal_strength', models.CharField(choices=[('weak', 'Weak'), ('moderate', 'Moderate'), ('strong', 'Strong'), ('very_strong', 'Very Strong')], max_length=20)),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('target_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_profit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
                ('reasoning', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trading_pair', 'signal_type'], name='alerts_trad_trading_300a18_idx'), models.Index(fields=['signal_source', 'is_active'], name='alerts_trad_signal__023da0_idx'), models.Index(fields=['created_at'], name='alerts_trad_created_baa8b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('market_crash', 'Market Crash'), ('bull_run', 'Bull Run'), ('high_volatility', 'High Volatility'), ('low_liquidity', 'Low Liquidity'), ('exchange_issue', 'Exchange Issue'), ('regulatory_news', 'Regulatory News'), ('security_alert', 'Security Alert')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical'), ('emergency', 'Emergency')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('affected_pairs', models.JSONField(blank=True, default=list)),
                ('affected_exchanges', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_global', models.BooleanField(default=False)),
                ('requires_acknowledgment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='alerts_mark_categor_db4d91_idx'), models.Index(fields=['severity', 'is_active'], name='alerts_mark_severit_bbe985_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('max_alerts', models.IntegerField(default=5)),
                ('max_signals', models.IntegerField(default=10)),
                ('advanced_features', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('alerts_used', models.IntegerField(default=0)),
                ('signals_accessed', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AlertTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('trigger_conditions', models.JSONField(default=dict)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('in_app_sent', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='alerts.alert')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_triggers', to='alerts.tradingsignal')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['alert', 'triggered_at'], name='alerts_aler_alert_i_cfd28c_idx'), models.Index(fields=['triggered_at'], name='alerts_aler_trigger_e3fa43_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'status'], name='alerts_aler_user_id_286633_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['trading_pair', 'status'], name='alerts_aler_trading_e10457_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'status'], name='alerts_aler_alert_t_82e8cd_idx'),
        ),
    ]
