# Generated by Django 4.2.7 on 2025-10-05 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(choices=[('index', 'Index Investment'), ('single_crypto', 'Single Cryptocurrency'), ('dca', 'Dollar Cost Averaging'), ('hodl', 'Long-term Hold')], default='index', max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('total_invested_btc', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_invested_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('current_value_btc', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('current_value_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unrealized_pnl_btc', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('unrealized_pnl_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unrealized_pnl_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('all_time_high_value', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('max_drawdown_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('auto_compound', models.BooleanField(default=False)),
                ('dca_amount_btc', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('dca_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('next_dca_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='active', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('crypto_index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_portfolio', to='trades.cryptoindex')),
                ('cryptocurrency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_portfolio', to='trades.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit/Add Funds'), ('withdraw', 'Withdraw/Reduce Position'), ('compound', 'Compound Gains'), ('rebalance', 'Portfolio Rebalance'), ('dividend', 'Dividend/Reward Payment'), ('fee', 'Management Fee')], max_length=10)),
                ('amount_btc', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('btc_price_at_transaction', models.DecimalField(decimal_places=8, max_digits=20)),
                ('index_value_at_transaction', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('fees_btc', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('is_automatic', models.BooleanField(default=False)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investment')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_352b49_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['crypto_index', 'status'], name='investments_crypto__0eb680_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['cryptocurrency', 'status'], name='investments_cryptoc_4c27a7_idx'),
        ),
    ]
