# Generated by Django 4.2.7 on 2025-10-01 12:54

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('api_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('min_order_size', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('max_order_size', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('price_precision', models.IntegerField(default=2)),
                ('quantity_precision', models.IntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_pairs', to='market_data.exchange')),
            ],
            options={
                'ordering': ['symbol'],
                'unique_together': {('exchange', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='MarketDataAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('weighted_average_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('total_volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('number_of_exchanges', models.IntegerField()),
                ('price_volatility', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='market_data_symbol_997063_idx'), models.Index(fields=['timestamp'], name='market_data_timesta_0ed880_idx')],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_trade_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField()),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quote_quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('fee_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='market_data.tradingpair')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['trading_pair', 'timestamp'], name='market_data_trading_fee47c_idx'), models.Index(fields=['exchange_trade_id'], name='market_data_exchang_886453_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('last_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bid_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('ask_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('bid_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('ask_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('high_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('low_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('price_change_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('price_change_percent_24h', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='market_data.tradingpair')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['trading_pair', 'timestamp'], name='market_data_trading_4e39a3_idx'), models.Index(fields=['timestamp'], name='market_data_timesta_38ff82_idx')],
                'unique_together': {('trading_pair', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('side', models.CharField(choices=[('bid', 'Bid'), ('ask', 'Ask')], max_length=4)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_books', to='market_data.tradingpair')),
            ],
            options={
                'ordering': ['-timestamp', 'side', 'price'],
                'indexes': [models.Index(fields=['trading_pair', 'timestamp'], name='market_data_trading_f1243b_idx'), models.Index(fields=['trading_pair', 'side', 'price'], name='market_data_trading_30440f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quote_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('number_of_trades', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='market_data.tradingpair')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['trading_pair', 'timestamp'], name='market_data_trading_618060_idx'), models.Index(fields=['timestamp'], name='market_data_timesta_8a9a77_idx')],
                'unique_together': {('trading_pair', 'timestamp')},
            },
        ),
    ]
