# Generated by Django 4.2.7 on 2025-10-01 12:54

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('trading', 'Trading Reports'), ('portfolio', 'Portfolio Reports'), ('risk', 'Risk Reports'), ('compliance', 'Compliance Reports'), ('custom', 'Custom Reports')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('trading_summary', 'Trading Summary'), ('portfolio_performance', 'Portfolio Performance'), ('risk_analysis', 'Risk Analysis'), ('compliance_report', 'Compliance Report'), ('tax_report', 'Tax Report'), ('custom_report', 'Custom Report')], max_length=25)),
                ('default_parameters', models.JSONField(blank=True, default=dict)),
                ('template_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('requires_subscription', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20)),
                ('schedule_config', models.JSONField(blank=True, default=dict)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', max_length=10)),
                ('email_recipients', models.JSONField(blank=True, default=list)),
                ('auto_delete_after_days', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='reports_sch_user_id_369fc7_idx'), models.Index(fields=['next_run', 'is_active'], name='reports_sch_next_ru_5120c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('trading_summary', 'Trading Summary'), ('portfolio_performance', 'Portfolio Performance'), ('risk_analysis', 'Risk Analysis'), ('compliance_report', 'Compliance Report'), ('tax_report', 'Tax Report'), ('custom_report', 'Custom Report')], max_length=25)),
                ('permission_type', models.CharField(choices=[('view', 'View'), ('generate', 'Generate'), ('schedule', 'Schedule'), ('export', 'Export'), ('admin', 'Admin')], max_length=20)),
                ('is_granted', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('max_reports_per_day', models.IntegerField(blank=True, null=True)),
                ('max_file_size', models.BigIntegerField(blank=True, null=True)),
                ('allowed_formats', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'report_type'],
                'unique_together': {('user', 'report_type', 'permission_type')},
            },
        ),
        migrations.CreateModel(
            name='ReportAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('trading_summary', 'Trading Summary'), ('portfolio_performance', 'Portfolio Performance'), ('risk_analysis', 'Risk Analysis'), ('compliance_report', 'Compliance Report'), ('tax_report', 'Tax Report'), ('custom_report', 'Custom Report')], max_length=25)),
                ('reports_generated', models.IntegerField(default=0)),
                ('total_file_size', models.BigIntegerField(default=0)),
                ('average_generation_time', models.FloatField(blank=True, null=True)),
                ('success_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('average_file_size', models.BigIntegerField(blank=True, null=True)),
                ('last_generated', models.DateTimeField(blank=True, null=True)),
                ('most_used_format', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], max_length=10, null=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('user', 'report_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('trading_summary', 'Trading Summary'), ('portfolio_performance', 'Portfolio Performance'), ('risk_analysis', 'Risk Analysis'), ('compliance_report', 'Compliance Report'), ('tax_report', 'Tax Report'), ('custom_report', 'Custom Report')], max_length=25)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('date_range_start', models.DateTimeField(blank=True, null=True)),
                ('date_range_end', models.DateTimeField(blank=True, null=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'report_type'], name='reports_rep_user_id_f11f57_idx'), models.Index(fields=['status', 'created_at'], name='reports_rep_status_22ec20_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('trades', 'Trades Export'), ('orders', 'Orders Export'), ('positions', 'Positions Export'), ('portfolio', 'Portfolio Export'), ('transactions', 'Transactions Export'), ('custom', 'Custom Export')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('date_range_start', models.DateTimeField(blank=True, null=True)),
                ('date_range_end', models.DateTimeField(blank=True, null=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='csv', max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('record_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'export_type'], name='reports_exp_user_id_11ab5f_idx'), models.Index(fields=['status', 'created_at'], name='reports_exp_status_b9ce26_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('widget_type', models.CharField(choices=[('chart', 'Chart'), ('metric', 'Metric'), ('table', 'Table'), ('gauge', 'Gauge'), ('progress', 'Progress Bar'), ('custom', 'Custom Widget')], max_length=20)),
                ('chart_type', models.CharField(blank=True, choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('pie', 'Pie Chart'), ('doughnut', 'Doughnut Chart'), ('area', 'Area Chart'), ('candlestick', 'Candlestick Chart')], max_length=20, null=True)),
                ('data_source', models.CharField(max_length=100)),
                ('data_config', models.JSONField(blank=True, default=dict)),
                ('display_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('refresh_interval', models.IntegerField(blank=True, null=True)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=6)),
                ('height', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position_y', 'position_x'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='reports_das_user_id_60ff9e_idx')],
            },
        ),
    ]
